spring.application.name=e-commerce

# H2 Database (se reinicia al parar la app)
# spring.datasource.url=jdbc:h2:mem:gamertech_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gamertech_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# # Connection Pool Configuration
# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=5
# spring.datasource.hikari.idle-timeout=300000

# JWT Configuration
# Clave secreta para firmar los tokens (IMPORTANTE: Cambia esto en producción con una clave segura)
# Esta es una clave de ejemplo codificada en Base64 de 256 bits
jwt.secret.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Tiempo de expiración del token en milisegundos (24 horas = 86400000 ms)
jwt.expiration=86400000
